config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'streams/new'
  get 'streams/edit'
  get 'streams/show'
  get 'streams/index'

  get 'activities/new'
  get '/new-activity' => 'activities#new'
  get 'activities/show'
  get 'activities/index'
  get 'activities/edit'

  get 'sessions/new'
  get '/login' => 'sessions#new'

  get 'users/new'
  get '/signup' => 'users#new'
  get 'users/show'
  get 'users/edit'
  get 'users/index'

  resources :users
  resources :activities
  resources :streams

  get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'pages/pro'

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :streams
	validates :name, :description, presence: true
	has_attached_file :image,
                    styles: { normal: '364x220#', thumb: '32x32#', medium: '64x64#' }
                    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  validates :first_name, :last_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :username, presence: true, length: { minimum: 3, maximum: 32 }                  
	has_secure_password
	validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
	has_attached_file :image,
                    styles: { normal: '180x180#', thumb: '32x32#', medium: '64x64#' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_many :streams

	def full_name
    first_name.capitalize + " " + last_name.capitalize
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

 def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

 

def User.new_token
    SecureRandom.urlsafe_base64
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


private

def downcase_email
	self.email = email.downcase
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
  	@activity = Activity.new
  end

  def create
  	@activity = Activity.new(activity_params)
  	if @activity.save
  		redirect_to @activity
  	else
  		render 'new'
  	end
  end

  def show
  end

  def index
    @activities = Activity.all.order('name ASC')
  end

  def edit
  end

  private

  def activity_params
  	params.require(:activity).permit(:name, :description, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
   private

 def logged_in_user
      unless logged_in?
      	store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def pro
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
else
  	flash.now[:danger] = 'Invalid email or password' # create error message
  	render 'new'
  end
end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  require "opentok"
  include ActionController::Live

  def new
  	if !logged_in?
  		redirect_to login_path
    else
      @stream = Stream.new
  	end
  end

  def create
    @stream = current_user.streams.build(stream_params)
    @stream.activity_id = params[:activity_id]
    if @stream.save
      @stream.save
      redirect_to @stream
    else
      puts "#{@stream.errors.full_messages}"
      render 'new'
    end
  end

  def edit
  end

  def show
    @stream = Stream.find(params[:id])
    start_stream
  end

  def index
  end

   def start_stream
        # Replace with your OpenTok API key:
        api_key = "45793422"
        # Replace with your OpenTok API secret:
        api_secret = "21bdd1ff828e42ebb1b21755d39b1d4307be5a88"

        opentok = OpenTok::OpenTok.new api_key, api_secret 
        session = opentok.create_session :media_mode => :routed
        session_id = session.session_id
        token = session.generate_token
        # archive = opentok.archives.create session

    end

    private

    def stream_params
      params.require(:stream).permit(:title, :description)
      
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
		log_in @user
		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def index
  end

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :username, :image, :tagline, :bio)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

# def forget(user)
#     user.forget
#     cookies.delete(:user_id)
#     cookies.delete(:remember_token)
#   end

def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


def logged_in?
    !current_user.nil?
  end

  def log_out
    # forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
    if user && user.authenticated?
      log_in user
      # @current_user = user
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/edit.html.erb
<h1>Activities#edit</h1>
<p>Find me in app/views/activities/edit.html.erb</p>

app/views/activities/index.html.erb
<h1>All Activities</h1>
<p>Find me in app/views/activities/index.html.erb</p>
<!-- Show index of 'games' as activities -->
<% @activities.each do |a| %>
    <%= link_to (image_tag a.image.url(:normal)), a %><br>
	<%= link_to "#{a.name}", a %><br>
<% end %>

app/views/activities/new.html.erb
<h1>Create Activity</h1>
<%= form_for(@activity) do |f| %>
  <%= f.text_field :name, placeholder: 'Name of Activity' %><br>
  <%= f.text_area :description, placeholder: 'Describe this activity ...' %><br>
  <%= f.file_field :image %><br>
  <%= f.submit 'Create Activity' %>
<% end %>

app/views/activities/show.html.erb
<h1>Live Channels for (this activity)</h1>
<p>Find me in app/views/activities/show.html.erb</p>
<!-- Show Streams where activity_id == activity you clicked on -->

app/views/layouts/_header.html.erb
<ul>
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Start New Stream", streams_new_path %></li>
	<li><%= text_field_tag :search, nil, placeholder: 'Search Activities ...' %></li>
	<% if !logged_in? %>
	<li><%= link_to "Log In", login_path %></li>
	<% end %>
	<% if logged_in? %>
	<li><%= link_to "#{current_user.username}", user_path(current_user) %></li>
	<li><%= link_to "Settings", "#" %></li>
	<li><%= link_to logout_path, method: :delete do %>
                 		        	<span class="fa fa-sign-out"></span> Log out
                 		        	<% end %>

	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title>VideoHack</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grunge - Video Hack Day 2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
   <div id="container" style="left: 0px;">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Grunge</h1>
<p>Who you are is what you do</p>
<%= link_to "Sign Up", signup_path %>
<%= link_to "Browse", activities_path %>

app/views/pages/pro.html.erb
<h1>Pages#pro</h1>
<p>Find me in app/views/pages/pro.html.erb</p>

app/views/streams/edit.html.erb
<h1>Streams#edit</h1>
<p>Find me in app/views/streams/edit.html.erb</p>

app/views/streams/index.html.erb
<h1>Streams#index</h1>
<p>Find me in app/views/streams/index.html.erb</p>
<!-- Show streams related to the activity_id -->

app/views/streams/new.html.erb
<h1>Start a New Livestream</h1>
<p>What activity are you about to stream?</p>

<%= form_for @stream do |f| %>
<input name="activity_id" value="<%= Activity.first.id  %>" type="hidden">
<%= f.text_field :title, placeholder: "Name this Stream" %><br>
<%= f.text_area :description, placeholder: "What will this stream be about?" %><br>

<p>
<%= f.submit 'GO LIVE' %>
</p>
<% end %>

app/views/streams/show.html.erb
<h1><%= @stream.title %></h1>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up for Grunge</h1>
<p>Share what you do with the world.</p>
<%= form_for @user do |f| %>

  <p><%= f.text_field :first_name, placeholder: 'First Name' %> <%= f.text_field :last_name, placeholder: 'Last Name' %></p>

  <%= f.email_field :email, placeholder: 'Email address' %><br>
  <%= f.text_field :username, placeholder: 'Create a Username' %><br>

  <%= f.password_field :password, placeholder: 'Create a password' %><br>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %><br>

<p>
  <%= f.submit %>
</p>
<% end %>